version: 0.2
            
phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build:prod
  post_build:
    commands:
      - aws s3 sync ./www s3://amiibos-ionic-angular --delete
artifacts:
  files:
    - '**/*'
  name: amiibos-ionic-angular
  base-directory: 'www'
